sudo: false
language: go
go:
  - 1.11
install:
  - go get -v github.com/spf13/hugo
  - (cd themes/hckspc-bootstrap && npm install && ./node_modules/.bin/bower install)
script:
  - export PATH=$HOME/gopath/bin:$PATH
  - hugo --theme=hckspc-bootstrap
cache:
  bundler: true
  directories:
    - themes/hckspc-bootstrap/node_modules
    - themes/hckspc-bootstrap/static/bower_components
deploy:
  local-dir: public/
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
  keep-history: true
  on:
    branch: master

